### ISSUE TITLE
Editorial name editing decisions

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-backend#139]
The CoL editor may need to modify spelling (e.g. misspelled genus name in a single binomial; misspelled species epithet ("crista galli" ->  "crista-galli"); misspelled species author; etc.).

Open questions:
 - is this really an editorial decision or rather a feedback to the source?
 - how should this be implemented. An editorial decision to update the name/author spelling during the assembly or maybe rather sth that modifies the names index which gets used during the assembly?

**Comment by mdoering** [comment]
@yroskov could you provide examples of the various corrections? Especially what does misspelled `genus name in a single binomial` refer to? Are these zoological names being the species epithet alone?

**Comment by yroskov** [comment]
One example is correction in misspelled authorstring (N.E. Brown over misspelled N.F. Brown)

Here is my illustration to “misspelled genus name in a single binomial”:

Genus Hammatolobium was misspelled with one of its species as Hamatolobium, so  H. kremerianum and H. lotoides were placed in two different genera. This bug need to be corrected in CoL, because ILDIS has no software to host their data and cannot do correction.

>> zoological names being the species epithet alone

It’s another case. CoL is detecting species records with empty Genus field and excluding them from an import.

Yuri

**Comment by mdoering** [comment]
Ideally we should probably have a taxonomic editor for datasets in the Clearinghouse that can be used to manage proto GSDs as well as datasets like ILDIS lacking a working environment. I've created a dedicated issue #144 for such a discussion.

If such an editor would exist, do you still think there is the need to manipulate names in the CoL?

**Comment by mdoering** [comment]
see also Dave: https://github.com/Sp2000/colplus/pull/1#issuecomment-425208271

**Comment by mdoering** [comment]
see #289 UPDATE name
