### ISSUE TITLE
the dataset model needs a logoUrl field

### ISSUE THREAD

**Issue by thomasstjerne** [Sp2000/colplus-backend#149]
https://sp2000.github.io/colplus/api/admin.html#model-Dataset

**Comment by mdoering** [comment]
already added ;)
https://github.com/Sp2000/colplus-backend/blob/be0d0159c34500486f4a70855e61503df6358a6d/colplus-api/src/main/java/org/col/api/model/Dataset.java#L35

**Comment by mdoering** [comment]
I have not included it in the ColSource class because I would like to expose a specific logo ws resource for each source so that the logo comes from the local services and is already resized properly. For the datasets we could do the same, but at least need to know where the logo is coming from. For the col sources these either come from the dataset or the CoL editor uploads them manually, but never configures an external URL

**Comment by mdoering** [comment]
see #151
