### ISSUE TITLE
Update classification for entire taxon subtree in ES

### ISSUE THREAD

**Issue by mdoering** [Sp2000/colplus-backend#330]
When a taxon is moved, i.e. its parent changed, or a new taxon is deleted, we need to update the classification of the entire subtree incl synonyms.

All other information stays the same in ES, just the classification (ids, rank and name) needs to be updated. 

The IndexingService should expose a new method that takes the datasetKey and taxonID of the root taxon that should be updated (and all its descendants). Instead of pulling all information again out of the db a new mybatis mapper method should be created that allows to process just the classification with a ResultHandler and which does a recursive iteration from root down just like we do for the full objects.

**Comment by mdoering** [comment]
Is ES good at doing partial updates? We had troubles with Solr at GBIF.

**Comment by mdoering** [comment]
See empty method NameUsageIndexServiceEs.updateClassification()

**Comment by ayco-at-naturalis** [comment]
Is there a reason we try to only update the ES documents? Because in reality there is no such thing in ES (or Lucene). Updating really amounts to deleting and then re-inserting.

Is it because you are afraid of all the extra PG joins, which aren't necessary if you only want the classification?

On the other hand, if you directlly pass in a name usage id (as the root of the tree) it should be very fast - unless in the unlikely case of changing entry kingdoms (or maybe large phylae). So the needless extra joins aren't that painful.

**Comment by ayco-at-naturalis** [comment]
Also: what you gain in performance from PG is somewhat undone by the extra work ES now has to do: retrieve a document, update uts classification, save it back.

Otherwise we could just blindly delete all documents that have the root id somewhere in there classification IDs. And then re-index the entire tree again

**Comment by mdoering** [comment]
yes, the pg overhead is what Id like to keep low. It seems very wasteful to ask for all the information with potentially many vernacular names, accepted taxon, verbatim issues etc. its not only many more joins with a much broader resultset, but due to vernaculars also many more records. 

Keeping a flat classification searchable while allowing taxa to change their parents is just not a good fit.

**Comment by ayco-at-naturalis** [comment]
On the PG there's now a NameUsageWrapperMapper.processTree method. Might want to rename that to processClassification, so that in the future processTree really hands over an entire subtree to ES (rather than just the classification). On the ES side there is a new ResultHandler: ClassificationUpdater.  Performance seems to be pretty OK. Tested it with the Insecta within Itis Global, which took about 10 seconds with PG needing somewhat more time than ES (didn't measure it accurately though)
