### ISSUE TITLE
Searching for binomials does not return trinomials

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#333]
This is probably already planned and just not implemented yet, but when [searching with a binomial](https://www.col.plus/dataset/2046/names?facet=rank&facet=issue&facet=status&limit=50&offset=0&q=Leptoiulus%20trilineatus), it's important that the trinomials of that binomial are returned in the search results just as in the [CoL public interface](http://www.catalogueoflife.org/col/search/all/key/Leptoiulus+trilineatus/fossil/1/match/1). (As a heads up, this example dataset does not include all of the infraspecies in CoL, but I'd expect *[Leptoiulus trilineatus nigra](https://www.col.plus/dataset/2046/names?facet=rank&facet=issue&facet=status&limit=50&offset=0&q=Leptoiulus%20trilineatus%20nigra)* to be returned when searching for *[Leptoiulus trilineatus](https://www.col.plus/dataset/2046/names?facet=rank&facet=issue&facet=status&limit=50&offset=0&q=Leptoiulus%20trilineatus)*.)

Oddly, when searching with just the species epithet, *trilineatus*, the [trinomials are returned but not the binomial](https://www.col.plus/dataset/2046/names?facet=rank&facet=issue&facet=status&limit=50&offset=0&q=trilineatus).

Ideally if search can return results for abbreviated genera (e.g., *[L. trilineatus](https://www.col.plus/dataset/2046/names?facet=rank&facet=issue&facet=status&limit=50&offset=0&q=L.%20trilineatus)*) and partial names (e.g., [neatus](https://www.col.plus/dataset/2046/names?facet=rank&facet=issue&facet=status&limit=50&offset=0&q=neatus))  that would be extremely useful, too. The [current CoL search only seems to be able to do partial match on the prefixes](http://www.catalogueoflife.org/col/search/all/key/Bono/fossil/1/match/0) and [not on suffixes](http://www.catalogueoflife.org/col/search/all/key/ineatus/fossil/1/match/0). In the past, the CoL public search was able to do [prefixes, middle parts of names, and suffixes](http://www.catalogueoflife.org/annual-checklist/2010/search/all/key/bono/match/0).

**Comment by mdoering** [comment]
Indeed this is wrong. Not sure why it does that, @ayco-at-naturalis would you expect this?

Binomial search only returns binomial
http://api.col.plus/dataset/2046/name/search?q=Leptoiulus%20trilineatus

even though the trinomial exists:
http://api.col.plus/dataset/2046/name/search?q=Leptoiulus%20trilineatus%20nigra

**Comment by mdoering** [comment]
Searching and ranking results is a tricky game.
Personally I would prefer a fuzzy token based search that allows to hit any part of the name with 1 fuzzy char match and the scientific name normalization which includes gender stemming and removal of silent h and double letters. It would not do prefix or suffix match as this yields entirely different results which are a very different use case in my mind. Prefix search should exist though as a separate service to support autocompletion. Maybe we need to spec out the search behavior better?

**Comment by ayco-at-naturalis** [comment]
This is odd, I suspect it has something to do with the maximum length of the tokens (ngrams) the sci name broken up into. I might be though that we need another analizer _besides_ the one we already have

**Comment by ayco-at-naturalis** [comment]
Looking closer into Geoff's remarks, it seems clear that Elasticsearch's auto-complete query does not satisfy our use case(s).

I currently see two possible ways ahead:

1. Use the auto-complete mechanism **only** for auto-completion i.e. to fill up the search box. Then the user has to press enter and a more heavy and savvy query mechanism is used. Probably straight ngram queries, or full-text search or both. This way auto-completion keeps working speedily. Since we only use it to help the user fill up the search box, we don't even need to apply the query constraints from the facets, so it may even work faster than now. This probably also requires some redesign of the frontend.

2. Ditch the auto-complete mechanism altogether in favour of ngrams/full-text search. In principle this is better, but it might be too heavy for auto-complete purposes.

**Comment by mdoering** [comment]
Like I have written in my remark above I believe we have 2 use case:
a) autocomplete, mostly for populating filter forms. This should do a prefix based search I think, matching on substrings of a token I dont think is really needed.

b) do the real search. Here I always thought we do regular token based searches with an analyzer that normalizes a name in a way we support fuzzy search for often misspelled cases (e.g. silent h y->i etc). That means only match on entire name tokens, not ngrams or other partial matches. I use token here in the sense of a lucene token stream that the analyzer produces. I.e. 4 tokens `Abies` `alba` `subsp` `alpina` are kept for the string `Abies alba subsp. alpina`

**Comment by mdoering** [comment]
separating these two into different services is probably wise to do

**Comment by ayco-at-naturalis** [comment]
Are you sure we don't need ngrams? With ngrams searches, too, the query string is brokup up along word boundaries, so it gives you to best of both worlds. If a user types (.e.g.) "rilinea", do we not want "Leptoiulus trilineatus nigra" to come back?

The "fuzzy" aspect of the search is accomplished by name normalization (which is already happening in the simple auto-complete phase by the way).

Note that both the weakly normalized and the strongly normalized names **are** already tokenized as it is. Only with tokens that start from the beginning of the word, which now seems to be our problem.

But anyway, yes, we should split the current service into a simple auto-complete service. That service might as well return a list of strings, rather than full-blown NameUsageWrapper instances.

Plus another service that implements what's discussed here.

**Comment by mdoering** [comment]
I don't think its very useful to search for `rilinea`. It might even clutter real results in some cases.
But as we lack proper use cases this is potentially wrong ;)

**Comment by mdoering** [comment]
and yes, the autocomplete could return sth really simple like a generic id & label object so we can reuse that for all autocompletions

**Comment by ayco-at-naturalis** [comment]
@mdoering question: the scientifc names ending up in the Name's scientificName field, do they include rank and/or hybrid markers? Or are these normalized away in the import process? If not, we should probably include them as "stop words" so their presence or absence in name has no influence on whether one name matches another.

If it is important that **all** such markers are filtered out, we must do it programmitically using the GBIF RankUtils class. If it's OK to only filter away to most common ones (like subsp.) - and take our chances with the rest - we can create an Elasticsearch stop word token filter.

If programmatically, this should then probably the **first** normalization, even before the SciNameNormalizer normalizations.

Then finally, to accomodate Geoff's request to match on abbreviated genus epithets, we must also store a version of the name (if sub-generic) with the genus epithet, eh, abbreviated. This is not necessary while the user has typed less characters than the maximum ngram token length. However, as this issue makes clear, after that we must switch to another analyzer, probably a combination of straight lowercase comparison and the standard (full-text) analyzer.

Note that there is always an area, between the maximum ngtam token length and the full length of a specific or subspecific epithet, where all matches suddenly disappear, because neither the auto-complete analyzer, nor the full-text analyzer, nor lowercase comparison (from the start) will work, But well ... it's search

What is your take on this?

**Comment by mdoering** [comment]
the name.scientificName is generated from the parsed name parts using the NameFormatter which should include the hybrid sign and rank markers. Also quotes for cultivars and other non regular latin bits. The scientificName can also be just anything in case of unparsable names, e.g. virus names.

For parsed names it is easy to generate a canonical name that excludes all of the above. 
Just use the NameFormatter to generate the simplest possible string, e.g a bi/trinomial with nothing else. See various Name.canonicalName() methods. Said that I am not exactly sure why we would want to do that. I would need more time to dive into the search details again.

**Comment by ayco-at-naturalis** [comment]
It's just so that if the user types "Larus fuscus fuscus" and the scientific name happens to be "Larus fuscus subsp. fuscus", that still counts as a 100% match. Anyway, I will skip this part for now, and only include the name-with-abbreviated-genus version in the index

**Comment by mdoering** [comment]
yes. And if a user types "Larus fuscus" it should also hit 100% names such as "Larus maritima var. fuscus". Ranking the various 100% matches is yet another problem. The higher the taxonomic rank the better I think. And the closer to the start of the name string the better. So "Larus fuscus var. maritima" should rank lower I reckon. But thats not crucial now, most ordering the UI uses will be alphabetically anyways

**Comment by mdoering** [comment]
btw, here is the EDIT CDM name search Yuri mentioned that he liked best in Rome 2013:
http://api.cybertaxonomy.org/col/name_catalogue/fuzzy

I cannot get anonymous access to the code yet, but you can browse it:
https://cybertaxonomy.eu/cdmlib/source-repository.html

**Comment by mdoering** [comment]
EDIT CDM code is mirrored to github: https://github.com/cybertaxonomy/cdmlib
There are also docker images for the cdm-server: https://hub.docker.com/r/cybertaxonomy/cdm-server

**Comment by mdoering** [comment]
@ayco-at-naturalis can we close this?
