### ISSUE TITLE
Duplicate gives no result using "withDecision=true"

### ISSUE THREAD

**Issue by thomasstjerne** [Sp2000/colplus-backend#346]
Just after applying some decisions, it is not possible to get any data with decisions

**Comment by mdoering** [comment]
https://github.com/Sp2000/colplus-backend/commit/02acc5d81bc3f0d15aef4797ce12da93aef3810e

**Comment by gdower** [comment]
This seems to be an issue again. See [here](https://github.com/Sp2000/colplus-frontend/issues/478#issuecomment-570640191).

**Comment by mdoering** [comment]
Not really an issue with duplicates.
There are 1227 decsions for catalogue 3 and scarabs: 
https://api.catalogue.life/decision?datasetKey=3&subjectDecisionKey=1027

All of them appear to be _broken_, i.e. the subject is lacking an `id` property that is required to bind the decision to the actual name usage. Therefore these decisions do not show up on duplicates or other usage responses like the tree API: https://api.catalogue.life/decision?datasetKey=3&subjectDecisionKey=1027&broken=true

As you can see in the [logs](https://logs.gbif.org/app/kibana#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-12h,mode:quick,to:now))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWyLao3iHCKcR6PFXuPR,key:logger_name,negate:!f,type:phrase,value:life.catalogue.dao.SubjectRematcher),query:(match:(logger_name:(query:life.catalogue.dao.SubjectRematcher,type:phrase))))),index:AWyLa4mQHCKcR6PFXu4X,interval:auto,query:(match_all:()),sort:!('@timestamp',desc))) none of the decisions did match.

**Comment by gdower** [comment]
Something seems off then, because the decisions were applied to the 2019-03-28 version of scarabs, which was replaced by the 2019-05-28 version but then when we saw no decisions we re-imported the 2019-03-28 version, so the decisions should match.

**Comment by mdoering** [comment]
The [logs](https://logs.gbif.org/app/kibana#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-12h,mode:quick,to:now))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWyLao3iHCKcR6PFXuPR,key:logger_name,negate:!f,type:phrase,value:life.catalogue.dao.SubjectRematcher),query:(match:(logger_name:(query:life.catalogue.dao.SubjectRematcher,type:phrase))))),index:AWyLa4mQHCKcR6PFXu4X,interval:auto,query:(match_all:()),sort:!('@timestamp',desc))) complain about duplicate names so the decision cannot clearly be matched to one of the multiple usages: 

> EditorialDecision 4194 cannot be rematched to dataset 1027 - multiple names like SPECIES Copris graueri

**Comment by gdower** [comment]
Hmm, I wonder why there's no ID's in the decisions? Maybe it is a frontend bug after all?

**Comment by gdower** [comment]
I'll try to delete out the decisions and try again while watching what the frontend is sending to the API.

**Comment by mdoering** [comment]
the ids is created by the import matching based on the other subject props.
But there are only logs for 25 duplicate names, so the other 12xx should be fine. Smells like a true bug...

**Comment by mdoering** [comment]
found it

**Comment by mdoering** [comment]
takes me ~30 minutes to deploy again

**Comment by gdower** [comment]
Alright, we'll try again after you deploy.

**Comment by gdower** [comment]
I deleted out all previous Scarabs decisions, and @yroskov re-applied the decisions to the 2019-03-28 version of Scarabs again, and then I re-imported the 2019-05-28 version and the decisions are still not remembered. I think the decisions had IDs, but then when we imported the 2019-05-28 version, the decisions might have lost their IDs. I'm double checking that now, because it seems strange.

The frontend is properly posting the decisions with IDs:

```JSON
{
  "datasetKey": 3,
  "subjectDatasetKey": "1027",
  "subject": {
    "id": "22-.01-.05-.01-.002-.000-.102-.-",
    "name": "Amphimallon subparallelum",
    "authorship": "(Escalera, 1914)",
    "rank": "species"
  },
  "mode": "update",
  "status": "provisionally accepted"
}
```

**Comment by mdoering** [comment]
not deployed yet ;)

**Comment by mdoering** [comment]
not it is on both envs

**Comment by gdower** [comment]
I just re-tried it on dev where it was deployed (Backend version: 5409fd4 January 3, 2020 3:40 PM) and the subject IDs actually did [disappear](https://api.dev.catalogue.life/decision?dataset=3&subjectDataset=1027) when the 2019-05-28 version was imported.

**Comment by gdower** [comment]
Nevermind, it worked on prod.

**Comment by mdoering** [comment]
The [logs](https://logs.gbif.org/app/kibana#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-30m,mode:quick,to:now))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWyLa2lBHCKcR6PFXu26,key:logger_name,negate:!t,type:phrase,value:http.request),query:(match:(logger_name:(query:http.request,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWyLa2lBHCKcR6PFXu26,key:logger_name,negate:!f,type:phrase,value:life.catalogue.dao.SubjectRematcher),query:(match:(logger_name:(query:life.catalogue.dao.SubjectRematcher,type:phrase))))),index:AWyLa2lBHCKcR6PFXu26,interval:auto,query:(match_all:()),sort:!('@timestamp',desc))) claim that the names of the 52 decisions do not exist in the dataset. Please always check the logs, filtering by the logger name `life.catalogue.dao.SubjectRematcher` helps.

Checking the first log entry manually I see:
 - [decision 3](http://api.dev.catalogue.life/decision/3): `SPECIES Anisoplia villosa Faldermann, 1836`
 - search for [Anisoplia villosa](https://api.dev.catalogue.life/dataset/1027/nameusage/search?q=Anisoplia%20villosa) returns one usage with a different name: `Anisoplia villosa (Goeze, 1777) Schoolmeesters P.`
=> so no match is expected behavior in that case.

Decision [52](http://api.dev.catalogue.life/decision/52), `Clinteria malayensis Gestro, 1888` also has a [different authorship Wallace, 1867](https://api.dev.catalogue.life/dataset/1027/nameusage/search?q=Clinteria%20malayensis) now, so a broken decision is expected.


subject IDs only ever remain if the matching succeeds. Otherwise they get nulled to indicate broken decisons. Thats by design.

**Comment by gdower** [comment]
> subject IDs only ever remain if the matching succeeds. Otherwise they get nulled to indicate broken decisons. Thats by design.

Ah, that makes more sense.
