### ISSUE TITLE
Language not specified for transliterations

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#430]
When transliterating common names, we should specify the language of the transliteration. Also, some common names that are presumably being transliterated to English still include diacritics like the clubmoss, [Keulenbärlapp](http://ower.org/col_diff/diff.php?id=2d8bc2f594625a8f5a6a508a9dfa86d0).

**Comment by yroskov** [comment]
If language is not pointed in the CoL, automatic transliteration should be blocked.

**Comment by mdoering** [comment]
[transliteration](https://en.wikipedia.org/wiki/Transliteration) is between scripts, not necessarily languages. So I am that sure if we should require a language for it happen.

As for the `Keulenbärlapp` the Latin script in ICU appears to include Umlauts.
We can easily remove them or even translate them to the correct German way:
https://www.filebot.net/forums/viewtopic.php?t=5459

Do we finally only want ASCII letters?

**Comment by yroskov** [comment]
Yes, we want only ISO Basic Latin Alphabet (basic ASCII letters) in "Transliteration" field. DIN5007-2 Transliterator looks as a good solution.

**Comment by mdoering** [comment]
Ok, I will transliterate everything to plain ASCII then.
I just thought its fine to keep accents on latin characters as they are still "readable" and more expressive then plain ASCII. For example:

`豹紋多紀魨` -> `bào wén duō jì tún`

instead of 
`豹紋多紀魨` -> `bao wen duo ji tun`

Please reconsider this, personally I would go for the latin alphabet but keep the accents

**Comment by yroskov** [comment]
Yes, only ASCII letters in the transliteration, pls.
