### ISSUE TITLE
Syncing a parent sector causes nested sectors to disappear

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#438]
After syncing [Fabaceae](https://dev.col.plus/assembly?assemblyTaxonKey=f322bed4-5aee-4492-96d6-bf57416e2640) the nested sectors from WWW and World Plants disappeared.

You can reproduce the bug by [syncing Diptera on dev](https://dev.col.plus/assembly?assemblyTaxonKey=1ead4a55-ff57-442d-9395-cec2eac468fe), which will cause the nested sector for the Tipuloidea superfamily from CCW to disappear from assembly. I confirmed this on prod already. The CCW sector is actually still there though if you use the [taxonKey](https://www.col.plus/assembly?assemblyTaxonKey=1cbbc0c2-d67b-46fc-99cc-c45cea12c58f). If you compare the API trees [before](https://api-dev.col.plus/dataset/3/tree/1ead4a55-ff57-442d-9395-cec2eac468fe/children?limit=100&offset=0) (dev) and [after](https://api.col.plus/dataset/3/tree/06c71274-e47f-4228-b99a-237b1661e1c4/children?limit=100&offset=0) (prod) sync the Tipuloidea superfamily sector provided by CCW sector is missing after the sync was done, so I think it's a backend bug. I'm not sure if it matters but the taxonIDs in the before (06c71274-e47f-4228-b99a-237b1661e1c4) and after (1ead4a55-ff57-442d-9395-cec2eac468fe) URLs above also changed.

**Comment by mdoering** [comment]
I have created some small fake nested sectors on dev based on Microsporidia and underneath the Asteraceae family from the ColDP example. It is working as expected even with subsequent syncs.

One thing to note is that when a sync starts the nested sectors and "foreign children" from other sectors are temporarily moved to the synced sectors parent so that they are out of the way. So they should disappear from the current view, but come back as soon as the sync is done.
