### ISSUE TITLE
Name search - odd results

### ISSUE THREAD

**Issue by thomasstjerne** [Sp2000/colplus-backend#504]
I may have spotted some odd behaviour in the name search.
if I search for "Holophrya sp." [I get 198 results](https://api-dev.col.plus/dataset/2009/name/search?facet=rank&facet=issue&facet=status&limit=50&offset=0&q=Holophrya%20sp.) but I cant figure out how any of them match "Holophrya sp.".

If I search for "Holophrya" [I find the one record I was after.](https://api-dev.col.plus/dataset/2009/name/search?facet=rank&facet=issue&facet=status&limit=50&offset=0&q=Holophrya)

**Comment by mdoering** [comment]
agree this is unexpected. Is `sp.` maybe hitting the authorships of those records?
`Sprengel`, `Sprague`

**Comment by ayco-at-naturalis** [comment]
Currently, for authors and vernacular names, the search terms ("holophrya" and "sp" - lowercased and with punction chopped off) get OR-ed, because that's the ES default. So yes, adding "sp." could increase the number of results.

Maybe for our purposes it's better to AND them. For scientific names the logic is altogether more subtle, so we won't have the problem there.

**Comment by mdoering** [comment]
I would definitely vote for AND!
