### ISSUE TITLE
nameusage/search: total is always 10.000 

### ISSUE THREAD

**Issue by thomasstjerne** [Sp2000/colplus-backend#583]
Even though facets of e.g. Rank=Genus gives 177.000

https://api.dev.catalogue.life/dataset/3/nameusage/search?facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&limit=50&offset=0&sortBy=taxonomic

**Comment by ayco-at-naturalis** [comment]
That must be because the "max_result_window" settings is 10000. ES (being a search engine) simply stops searching after that. It still surprises may because I (vaguely) remember that in previous versions an (not 100% guarantee) estimate of the total number of docs was given. If this is important then we must do both a count and a query

**Comment by mdoering** [comment]
this is important. But I am surprised too that ES doesnt give back at least a close estimate of the total hits. Lucene does that (or used to at least)

**Comment by mdoering** [comment]
maybe this one? https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-7.0.html#search-max-buckets-cluster-setting

**Comment by ayco-at-naturalis** [comment]
Ah ... nice, will build that one in

**Comment by ayco-at-naturalis** [comment]
track_total_hits now implicitly set to true unless explicitly specified otherwise

**Comment by mdoering** [comment]
@ayco-at-naturalis where in the code is this?
I just deployed the latest and I still get 10000 counts and there is no occurrence of `track_total_hits` in the code

**Comment by mdoering** [comment]
when closing please leave a commit of the main fix

**Comment by mdoering** [comment]
its also on the frontpage of the clearinghouse
