### ISSUE TITLE
Add BROKEN_DELIMINATOR issue

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#610]
See https://github.com/Sp2000/colplus-backend/issues/609#issuecomment-572730183

**Comment by mdoering** [comment]
CSV rows with less columns are skipped, so there is no verbatim record to attach an issue to.
The [logs](https://logs.gbif.org/app/kibana#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-30d,mode:quick,to:now))&_a=(columns:!(_source),index:AWyLa2lBHCKcR6PFXu26,interval:auto,query:(query_string:(query:'%22skip%20line%22')),sort:!('@timestamp',desc))) contain all skipped lines for imports.

To get a better handle on these usually very bad frameshift problems we could:
 - A) attach an issue to the previous and/or next record as they are usually effected too
 - B) keep the number of skipped & broken CSV records in the import statistics, plus maybe some 10 or so example line numbers where the problem is found. The frontend could integrate these with the other issue but make them not clickable (there is not verbatim record to show)

**Comment by gdower** [comment]
I think those approaches make sense, especially A since it would show up in the GSD issue matrix, making it easier to keep an eye out for broken delimination catalogue-wide.

**Comment by mdoering** [comment]
I will add an issue PREVIOUS_LINE_SKIPPED to the following record.
We could also mark all records that have more columns then the first row.
