### ISSUE TITLE
Allow exports of non-managed datasets

### ISSUE THREAD

**Issue by gdower** [Sp2000/colplus-backend#611]
When trying to export a non-managed dataset in the admin panel, I get the error:

```Only managed datasets can be assembled. Dataset 1027 is of origin EXTERNAL```

It would be really useful to be able to export other dataset types to the workbench for dataset testing and development purposes. If I change the dataset to managed, I can export it successfully so it doesn't seem like there's any constraint other than currently not allowing it. I suppose garbage collection might become an issue over time, but we could probably automatically delete exports older than 2 weeks.

**Comment by mdoering** [comment]
The thinking simply was that there are no sectors and thus credits.
I can try and remove the restriction to see what happens.

In general we should have ColDP exports for any datasets

**Comment by mdoering** [comment]
gonna add a new resource `/dataset/{key}/export` that you can POST to trigger an export of any dataset.
@thomasstjerne we should change the UI to use this method and remove the one under assembly then as the assembly resource is only meant for methods for catalogues

In the future we can add a new format parameter so that you can chose to export AC, ColDP or DwCA
