### ISSUE TITLE
Scope sectors in tree API

### ISSUE THREAD

**Issue by thomasstjerne** [Sp2000/colplus-backend#633]
When a managed dataset is used as source for another managed dataset, the tree API should only have sectorKeys related to the target dataset.

Example:

Working on assembly 31446 using the draft [3] as source, tree APIs are called as:

`https://api.dev.catalogue.life/dataset/3/tree/63e291b2-9018-4cdb-a599-ed6404d06ab4/children?limit=1000&offset=0&insertPlaceholder=true&catalogueKey=31446`

But the result is also decorated with sectorKeys targeting draft[3]:

![sectorsDraft](https://user-images.githubusercontent.com/1666484/74938585-9415cd00-53ee-11ea-89d9-1a3d012d48f7.png)

**Comment by mdoering** [comment]
The problem is that `TreeNode.sectorKey` is used for both the subject of a sector and the sectorKey of the name_usage from where it originated. When we only had one catalogue this was fine as a dataset was either the catalogue or a source. If we want to support this I think we should have 2 dedicated fields for the 2 situations. @thomasstjerne how about:

 - sectorKey if the usage originated from a certain sector
 - subjectSectorKey if it is the subject of a sector in the given catalogue/project

**Comment by mdoering** [comment]
Alternatively we could also add a new parameter to the API that defines whether the tree is rendered as source (right) or assembled (left)

**Comment by thomasstjerne** [comment]
Both would work, but I guess a parameter telling whether the tree is source or target might help solve similar problems, such as decisions.
Sth like
`treeType=target` or `treeType=source`

**Comment by mdoering** [comment]
ok, then I'll prepare to add such a new parameter to the tree API.
We could even exclude all sector & decision information in a tree if the parameter is missing in case someone just wants to browse the tree efficiently.

**Comment by mdoering** [comment]
New `type` query parameter added to all tree API resources.
It takes values `SOURCE` or `CATALOGUE` from http://api.dev.catalogue.life/vocab/treenode$type
