### ISSUE TITLE
Allow insertPlaceholder in tree API

### ISSUE THREAD

**Issue by thomasstjerne** [Sp2000/colplus-backend#642]
The new taxon drilldown breaks when there are placeholder nodes on the way down in the tree:
https://data.catalogue.life/catalogue/3/assembly?assemblyTaxonKey=035010ac-91b6-4c5d-8969-6da301b09652

Would it be possible to allow `insertPlaceholder=true` for this request?
https://api.catalogue.life/dataset/3/tree/035010ac-91b6-4c5d-8969-6da301b09652?catalogueKey=3&type=CATALOGUE

The drill down breaks because none of [these nodes ](https://api.catalogue.life/dataset/3/tree/0a3df756-a28c-48d0-b04c-193ee58b3579/children?limit=1000&offset=0&insertPlaceholder=true&catalogueKey=3&type=CATALOGUE)(a superfamily and a placeholder) are in the classification from the first request.

So if the placeholder superfamily was put in to the first tree response, it would work. 
```
{
"datasetKey": 3,
"id": "0a3df756-a28c-48d0-b04c-193ee58b3579--incertae-sedis--SUPERFAMILY",
"name": "Not assigned",
"rank": "superfamily",
"status": "accepted",
"childCount": 170,
"sectorKey": 4423
}
```

**Comment by mdoering** [comment]
Thats gonna be nasty cause I would need to know about all the children on every parent node to know if I need to create placeholder nodes. Could be done, but at a high performance cost.

Could the drill down not determine whether it needs to open a placeholder node?
In this case it open the order and is confronted with 2 superfamilies. It wants to reach a family next, so you know it must be inside the placeholder. Otherwise you would have retrieved a properly named superfamily in the first call.

**Comment by thomasstjerne** [comment]
I thought so. I will try, its tricky frontend-wise also, so I just wanted to check if it was easy in for you before I start working on it.

**Comment by mdoering** [comment]
if its not gonna work please reopen

**Comment by thomasstjerne** [comment]
solved
